
package soap.cibertec.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import soap.cibertec.interfaces.DistritoBean;
import soap.cibertec.interfaces.ViajeBean;
import soap.cibertec.interfaces.ObjectFactory;
import soap.cibertec.interfaces.ViajeBean;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sericio", targetNamespace = "http://interfaces.cibertec.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sericio {


    /**
     * 
     * @param sexo
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.ViajeBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllViajesXPrecio", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListAllViajesxPrecio")
    @ResponseWrapper(localName = "listAllViajesXSexoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListAllViajesXSexoResponse")
    @Action(input = "http://interfaces.cibertec.soap/sericio/listAllViajesXSexoRequest", output = "http://interfaces.cibertec.soap/sericio/listAllViajesXSexoResponse")
    public List<ViajeBean> listAllViajesXprecio(
        @WebParam(name = "precio", targetNamespace = "")
        double precioDesde, double precioHasta);

   

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.DistritoBean>
     */

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveViaje", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.SaveViaje")
    @ResponseWrapper(localName = "saveViajeResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.SaveViajeResponse")
    @Action(input = "http://interfaces.cibertec.soap/sericio/saveViajeRequest", output = "http://interfaces.cibertec.soap/sericio/saveViajeResponse")
    public int saveViaje(
        @WebParam(name = "Viaje", targetNamespace = "")
        ViajeBean Viaje);

    
   
   

    
    
}
